#!/usr/bin/env bash
# Verify task (Python / pytest). Generated by swe_bench_import.py.
set -uo pipefail

# Suppress setuptools-scm version detection failures (no .git in workdir).
export SETUPTOOLS_SCM_PRETEND_VERSION="0.0.1"

PASS=0; TOTAL=2

# --- Check 1: FAIL_TO_PASS tests now pass ----------------------------------
PYTEST_OUT="$(python3 -m pytest -k "test_Mul" -x --tb=short --ignore=bin 2>&1)"
if [[ $? -eq 0 ]]; then
  CHECK_F2P='{"passed": true, "details": "fail_to_pass tests now pass"}'
  PASS=$((PASS+1))
else
  F2P_ESC=$(printf '%s' "$PYTEST_OUT" | tail -20 | jq -Rs '.')
  CHECK_F2P=$(printf '{"passed": false, "details": %s}' "$F2P_ESC")
fi

# --- Check 2: PASS_TO_PASS tests still pass --------------------------------
PYTEST_P2P="$(python3 -m pytest -k "test_printmethod or test_Abs or test_Add or test_Catalan or test_ComplexInfinity" --tb=short --ignore=bin 2>&1)"
if [[ $? -eq 0 ]]; then
  CHECK_P2P='{"passed": true, "details": "pass_to_pass tests still pass"}'
  PASS=$((PASS+1))
else
  P2P_ESC=$(printf '%s' "$PYTEST_P2P" | tail -15 | jq -Rs '.')
  CHECK_P2P=$(printf '{"passed": false, "details": %s}' "$P2P_ESC")
fi

SCORE=$(awk -v p="$PASS" -v t="$TOTAL" 'BEGIN{printf "%.4f", p/t}')
[[ "$PASS" -eq "$TOTAL" ]] && SUCCESS="true" || SUCCESS="false"
cat <<EOF
{"success": $SUCCESS, "score": $SCORE, "checks": {"fail_to_pass": $CHECK_F2P, "pass_to_pass": $CHECK_P2P}}
EOF
[[ "$SUCCESS" == "true" ]] && exit 0 || exit 1
