#!/usr/bin/env bash
# Verify task (Django test runner). Generated by swe_bench_import.py + manual fix.
set -uo pipefail

PASS=0; TOTAL=2

# --- Check 1: FAIL_TO_PASS tests now pass ----------------------------------
F2P_OUT="$(python3 tests/runtests.py queries.test_q.QTests.test_combine_and_empty queries.test_q.QTests.test_combine_or_empty --verbosity=0 2>&1)"
if [[ $? -eq 0 ]]; then
  CHECK_F2P='{"passed": true, "details": "fail_to_pass tests now pass"}'
  PASS=$((PASS+1))
else
  F2P_ESC=$(printf '%s' "$F2P_OUT" | tail -20 | jq -Rs '.')
  CHECK_F2P=$(printf '{"passed": false, "details": %s}' "$F2P_ESC")
fi

# --- Check 2: PASS_TO_PASS tests still pass --------------------------------
P2P_OUT="$(python3 tests/runtests.py queries.test_q.QTests.test_combine_and_both_empty queries.test_q.QTests.test_combine_not_q_object queries.test_q.QTests.test_combine_or_both_empty queries.test_q.QTests.test_deconstruct queries.test_q.QTests.test_deconstruct_and --verbosity=0 2>&1)"
if [[ $? -eq 0 ]]; then
  CHECK_P2P='{"passed": true, "details": "pass_to_pass tests still pass"}'
  PASS=$((PASS+1))
else
  P2P_ESC=$(printf '%s' "$P2P_OUT" | tail -15 | jq -Rs '.')
  CHECK_P2P=$(printf '{"passed": false, "details": %s}' "$P2P_ESC")
fi

SCORE=$(awk -v p="$PASS" -v t="$TOTAL" 'BEGIN{printf "%.4f", p/t}')
[[ "$PASS" -eq "$TOTAL" ]] && SUCCESS="true" || SUCCESS="false"
cat <<EOF
{"success": $SUCCESS, "score": $SCORE, "checks": {"fail_to_pass": $CHECK_F2P, "pass_to_pass": $CHECK_P2P}}
EOF
[[ "$SUCCESS" == "true" ]] && exit 0 || exit 1
