#!/usr/bin/env bash
# Verify task (Python / pytest). Generated by swe_bench_import.py.
set -uo pipefail

PASS=0; TOTAL=2

# --- Check 1: FAIL_TO_PASS tests now pass ----------------------------------
PYTEST_OUT="$(python3 -m pytest "astropy/modeling/tests/test_separable.py::test_separable[compound_model6-result6]" "astropy/modeling/tests/test_separable.py::test_separable[compound_model9-result9]" -x --tb=short 2>&1)"
if [[ $? -eq 0 ]]; then
  CHECK_F2P='{"passed": true, "details": "fail_to_pass tests now pass"}'
  PASS=$((PASS+1))
else
  F2P_ESC=$(printf '%s' "$PYTEST_OUT" | tail -20 | jq -Rs '.')
  CHECK_F2P=$(printf '{"passed": false, "details": %s}' "$F2P_ESC")
fi

# --- Check 2: PASS_TO_PASS tests still pass --------------------------------
PYTEST_P2P="$(python3 -m pytest "astropy/modeling/tests/test_separable.py::test_coord_matrix" "astropy/modeling/tests/test_separable.py::test_cdot" "astropy/modeling/tests/test_separable.py::test_cstack" "astropy/modeling/tests/test_separable.py::test_arith_oper" "astropy/modeling/tests/test_separable.py::test_separable[compound_model0-result0]" --tb=short 2>&1)"
if [[ $? -eq 0 ]]; then
  CHECK_P2P='{"passed": true, "details": "pass_to_pass tests still pass"}'
  PASS=$((PASS+1))
else
  P2P_ESC=$(printf '%s' "$PYTEST_P2P" | tail -15 | jq -Rs '.')
  CHECK_P2P=$(printf '{"passed": false, "details": %s}' "$P2P_ESC")
fi

SCORE=$(awk -v p="$PASS" -v t="$TOTAL" 'BEGIN{printf "%.4f", p/t}')
[[ "$PASS" -eq "$TOTAL" ]] && SUCCESS="true" || SUCCESS="false"
cat <<EOF
{"success": $SUCCESS, "score": $SCORE, "checks": {"fail_to_pass": $CHECK_F2P, "pass_to_pass": $CHECK_P2P}}
EOF
[[ "$SUCCESS" == "true" ]] && exit 0 || exit 1
