import fs from 'fs';
import path from 'path';

export type BuildConfig = {
  entry: string;
  outDir: string;
  env?: Record<string, string>;
};

export function loadBuildConfig(configPath: string): BuildConfig {
  const absolute = path.resolve(configPath);
  const source = fs.readFileSync(absolute, 'utf8');
  if (absolute.endsWith('.json')) {
    return JSON.parse(source);
  }
  const module = { exports: {} as BuildConfig };
  // BUG: this only supports CommonJS configs. Workspace packages generated by
  // the newer scaffold use ESM `export default`, but switching the whole repo
  // to type:module breaks CommonJS packages.
  new Function('module', 'exports', source)(module, module.exports);
  return module.exports;
}

export function buildPackage(configPath: string): string {
  const config = loadBuildConfig(configPath);
  return `${config.entry} -> ${config.outDir}`;
}
